stages:
  - build
  - test
  - deploy
variables:
  AGAMA_ARTIFACT: build.tar.gz
  DOCKER_DRIVER: overlay2


build:
  image: asherd/agama-builder:windows
  stage: build
  script:
    - cd react
    - npm install
    - cd node_modules
    - rm -rf agama-wallet-lib
    - git clone https://github.com/VerusCoin/agama-wallet-lib.git -b dev --single-branch
    - cd ..
    - npm run build
    - "tar -czf $AGAMA_ARTIFACT build
    - mv build.tar.gz ..
  artifacts:
    paths:
    - build.tar.gz
    expire_in: 1 week


code_quality:
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]


deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  dependencies:
  - build
  script:
  - 'echo "$AUTH_KEY" > AUTH_KEY.json'
  - "gcloud auth activate-service-account --key-file AUTH_KEY.json"
  - "gsutil cp $AGAMA_ARTIFACT $STAGING/EasyDEX-GUI/$CI_COMMIT_REF_NAME/"
