sudo: false
os: linux
dist: trusty
language: node_js
node_js:
- lts/*
env:
  global:
  - CCACHE_SIZE=100M
  - CCACHE_COMPRESS=1
cache:
  apt: true

addons:
  apt:
    update: true
    sources:
    - sourceline: "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -c -s) main"
      key_url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      packages:
      - google-cloud-sdk

script:
- cd react
- npm install
- npm run build && cd ..

after_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_6b9be889f511_key -iv $encrypted_6b9be889f511_iv
  -in AUTH_KEY.json.enc -out AUTH_KEY.json -d && gcloud auth activate-service-account --key-file AUTH_KEY.json &&
  rm AUTH_KEY.json && rm AUTH_KEY.json.enc && tar -czvf build.tar.gz build &&
  gsutil cp build.tar.gz gs://$BUCKET/$PROJECT/$TRAVIS_BRANCH/;
  fi
