sudo: false
os: linux
dist: trusty
language: node_js
node_js:
- lts/*
env:
  global:
  - CCACHE_SIZE=100M
  - CCACHE_COMPRESS=1
cache:
  apt: true
  directories:
  - "$HOME/google-cloud-sdk/"

install:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash &>/dev/null; fi
- source /home/travis/google-cloud-sdk/path.bash.inc

script:
- ./make-build.sh

after_script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then openssl aes-256-cbc -K $encrypted_6b9be889f511_key -iv $encrypted_6b9be889f511_iv
  -in AUTH_KEY.json.enc -out AUTH_KEY.json -d && gcloud auth activate-service-account --key-file AUTH_KEY.json &&
  rm AUTH_KEY.json && rm AUTH_KEY.json.enc && tar -czvf build.tar.gz build &&
  gsutil cp build.tar.gz gs://$BUCKET/$PROJECT/$TRAVIS_BRANCH/;
  fi
